// Do not edit this file.

// Package metadata provides framework info registered to registry.
package metadata

// constant for sdk version, name, registration component
const (
	SdkVersion               = "1.1.3"
	SdkName                  = "Go-Chassis"
	SdkRegistrationComponent = "SDK"
)
