// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cse.proto

/*
Package cse is a generated protocol buffer package.

It is generated from these files:
	cse.proto

It has these top-level messages:
	CseInvokeRequest
	CseInvokeReply
*/
package cse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CseInvokeRequest struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age       string `protobuf:"bytes,3,opt,name=age" json:"age,omitempty"`
	Job       string `protobuf:"bytes,4,opt,name=job" json:"job,omitempty"`
	Delaytime int64  `protobuf:"varint,5,opt,name=delaytime" json:"delaytime,omitempty"`
	Number    int64  `protobuf:"varint,6,opt,name=number" json:"number,omitempty"`
	Version   string `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
}

func (m *CseInvokeRequest) Reset()                    { *m = CseInvokeRequest{} }
func (m *CseInvokeRequest) String() string            { return proto.CompactTextString(m) }
func (*CseInvokeRequest) ProtoMessage()               {}
func (*CseInvokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CseInvokeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CseInvokeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CseInvokeRequest) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *CseInvokeRequest) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *CseInvokeRequest) GetDelaytime() int64 {
	if m != nil {
		return m.Delaytime
	}
	return 0
}

func (m *CseInvokeRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *CseInvokeRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CseInvokeReply struct {
	InstantId  string `protobuf:"bytes,1,opt,name=instant_id,json=instantId" json:"instant_id,omitempty"`
	ResMessage string `protobuf:"bytes,2,opt,name=resMessage" json:"resMessage,omitempty"`
	Number     int64  `protobuf:"varint,3,opt,name=number" json:"number,omitempty"`
	Version    string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
}

func (m *CseInvokeReply) Reset()                    { *m = CseInvokeReply{} }
func (m *CseInvokeReply) String() string            { return proto.CompactTextString(m) }
func (*CseInvokeReply) ProtoMessage()               {}
func (*CseInvokeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CseInvokeReply) GetInstantId() string {
	if m != nil {
		return m.InstantId
	}
	return ""
}

func (m *CseInvokeReply) GetResMessage() string {
	if m != nil {
		return m.ResMessage
	}
	return ""
}

func (m *CseInvokeReply) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *CseInvokeReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*CseInvokeRequest)(nil), "cse.CseInvokeRequest")
	proto.RegisterType((*CseInvokeReply)(nil), "cse.CseInvokeReply")
}

func init() { proto.RegisterFile("cse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x24, 0xa6, 0x66, 0x0e, 0xa5, 0x0c, 0x22, 0x7b, 0x50, 0x29, 0x39, 0xf5, 0x94,
	0x8b, 0x6f, 0x50, 0x4f, 0x3d, 0x08, 0x25, 0x2f, 0x20, 0x9b, 0xcd, 0x50, 0xb6, 0x26, 0xbb, 0x71,
	0x67, 0x5b, 0xec, 0xd1, 0xd7, 0xf1, 0x29, 0x25, 0xdb, 0xaa, 0xf1, 0xe0, 0xed, 0xff, 0xbf, 0x81,
	0xe1, 0xe3, 0x87, 0x42, 0x33, 0x55, 0x83, 0x77, 0xc1, 0x61, 0xaa, 0x99, 0xca, 0x4f, 0x01, 0x8b,
	0x27, 0xa6, 0x8d, 0x3d, 0xba, 0x57, 0xaa, 0xe9, 0xed, 0x40, 0x1c, 0x70, 0x0e, 0x89, 0x69, 0xa5,
	0x58, 0x8a, 0x55, 0x51, 0x27, 0xa6, 0x45, 0x84, 0xcc, 0xaa, 0x9e, 0x64, 0x12, 0x49, 0xcc, 0xb8,
	0x80, 0x54, 0xed, 0x48, 0xa6, 0x11, 0x8d, 0x71, 0x24, 0x7b, 0xd7, 0xc8, 0xec, 0x4c, 0xf6, 0xae,
	0xc1, 0x3b, 0x28, 0x5a, 0xea, 0xd4, 0x29, 0x98, 0x9e, 0xe4, 0xd5, 0x52, 0xac, 0xd2, 0xfa, 0x17,
	0xe0, 0x2d, 0xe4, 0xf6, 0xd0, 0x37, 0xe4, 0x65, 0x1e, 0x4f, 0x97, 0x86, 0x12, 0x66, 0x47, 0xf2,
	0x6c, 0x9c, 0x95, 0xb3, 0xf8, 0xeb, 0xbb, 0x96, 0x1f, 0x02, 0xe6, 0x13, 0xd9, 0xa1, 0x3b, 0xe1,
	0x3d, 0x80, 0xb1, 0x1c, 0x94, 0x0d, 0x2f, 0x3f, 0xca, 0xc5, 0x85, 0x6c, 0x5a, 0x7c, 0x00, 0xf0,
	0xc4, 0xcf, 0xc4, 0x3c, 0xca, 0x9e, 0xfd, 0x27, 0x64, 0xe2, 0x90, 0xfe, 0xe7, 0x90, 0xfd, 0x71,
	0x58, 0x97, 0x70, 0x63, 0x5c, 0xb5, 0xf3, 0x83, 0xae, 0xe8, 0x5d, 0xf5, 0x43, 0x47, 0x5c, 0x69,
	0xa6, 0xf5, 0xb5, 0x66, 0xda, 0x8e, 0xbb, 0x6e, 0x45, 0x93, 0xc7, 0x81, 0x1f, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x74, 0xe7, 0xcd, 0x8c, 0x6d, 0x01, 0x00, 0x00,
}
